### ISSUE TITLE
Dynamically adding new IP address to the allowed list

### ISSUE THREAD

**Issue by ChampIsMe** [KennyTangHK/express-ip-access-control#3]
I have problem being able to dynamically add (white-list) a new IP address since I am the system admin. I have followed the documentation as it is and there is only an option to hard-code the list in the array before adding to the middle-ware.

**Comment by KennyTangHK** [comment]
Didn't expect this use case when designing this middleware.
This is not tested but may work for you.

```
var AccessControl = require('express-ip-access-control');

var denys = [];
var allows = [];
var options = { denys: denys, allows: allows };

var middleware = AccessControl(options);

var express = require('express');
var app = express();
app.use(middleware);

// Change denys and allows arrays
allows.push('127.0.0.1')
denys.pop()
```

**Comment by ChampIsMe** [comment]
Checking it out, thanks
